version: "3.4"
services:
  vite_docker:
    image: node:20-alpine
    container_name: timetostudy-api
    entrypoint: /bin/sh
    ports:
      - 80:3000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
    build:
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql
    container_name: mysql-tts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Volume para persistência de dados

volumes:
  db_data:
